[build]
build-std = true  # do not build the std library. has precedence over xargo
xargo     = true  # enable the use of xargo by default
zig       = false # do not use zig cc for the builds

[target.x86_64-unknown-linux-musl]
pre-build = [
  "apt-get update && apt-get --assume-yes install libssl-dev libpq-dev" ]
